### ISSUE TITLE
关于在CentOS下运行报错

### ISSUE THREAD

**Issue by G0doot** [TangBean/OnlineExecutor#11]
在MacOS下运行正常，但是放到CentOS下会报错，尝试了多个JDK版本，应该不是版本问题，感觉是编译上第一步在生成JavaFileManager出现了问题。

ERROR 19006 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at org.olexec.compile.StringSourceCompiler.compile(StringSourceCompiler.java:23) ~[classes!/:0.0.1-SNAPSHOT]
	at org.olexec.service.ExecuteStringSourceService.execute(ExecuteStringSourceService.java:32) ~[classes!/:0.0.1-SNAPSHOT]
	at org.olexec.controller.RunCodeController.runCode(RunCodeController.java:35) ~[classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_222]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
......

**Comment by G0doot** [comment]
找到了问题原因：https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6477844
